document.addEventListener('DOMContentLoaded', () => { // works so far?
  const chatToggle = document.querySelector('.ai-chat-toggle');
  const chatPanel = document.querySelector('.ai-chat-panel');
  if (!chatToggle || !chatPanel) return;

  const closeBtn = chatPanel.querySelector('.ai-chat-close');
  const form = chatPanel.querySelector('.ai-chat-input');
  const input = chatPanel.querySelector('input[name="message"]');
  const sendBtn = chatPanel.querySelector('.ai-chat-send');
  const messagesEl = chatPanel.querySelector('.ai-chat-messages');

  const apiKey =
    window.GROQ_API_KEY ||
    (document.body && document.body.dataset.groqKey) ||
    '';
  const modelCandidates = window.GROQ_MODEL
    ? [window.GROQ_MODEL]
    : ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant'];

  const BRAIN_PATHS = ['../brain.xd', '/brain.xd', './brain.xd', 'brain.xd'];
  const MAX_HISTORY_ITEMS = 8;
  const MAX_CONTEXT_CHARS = 2600;
  const MAX_REPLY_CHARS = 520;
  const LIVE_LOOKUP_TIMEOUT_MS = 6000;
  const LIVE_CONTEXT_MAX_CHARS = 3200;
  const VERIFIED_FACTS = {
    luzonPopulation2020: 64260312,
    philippinesPopulation2020: 109035343,
    centralLuzonPopulation2020: 12422172,
  };
  const REGION3_PROVINCES = [
    'aurora',
    'bataan',
    'bulacan',
    'nueva ecija',
    'pampanga',
    'tarlac',
    'zambales',
  ];
  const LUZON_TERMS = [
    'luzon',
    'central luzon',
    'region iii',
    'region 3',
    'aurora',
    'bataan',
    'bulacan',
    'nueva ecija',
    'pampanga',
    'tarlac',
    'zambales',
    'metro manila',
    'ncr',
    'quezon city',
    'manila',
    'cordillera',
    'baguio',
    'benguet',
    'ilocos',
    'pangasinan',
    'cagayan valley',
    'cagayan',
    'isabela',
    'batanes',
    'calabarzon',
    'cavite',
    'laguna',
    'batangas',
    'rizal',
    'quezon province',
    'mimaropa',
    'palawan',
    'mindoro',
    'bicol',
    'albay',
    'camarines',
    'sorsogon',
    'legazpi',
    'naga',
    'taal',
    'mayon',
  ];

  const SYSTEM_PROMPT = `
You are Luzonix, an assistant for the Region 3 Agriculture Portal.
Rules:
1) Use provided context (BRAIN_CONTEXT and CURRENT_PAGE_CONTEXT) first.
2) If context is incomplete, give the best possible short answer and label clearly as estimate/incomplete.
3) Never invent names, dates, offices, or statistics.
4) Keep answers concise: 2-5 short sentences unless the user asks for detail.
5) Prefer direct answers with year labels when numbers are involved.
6) For population questions, prioritize VERIFIED_FACTS if present.
7) If LIVE_CONTEXT exists, prioritize it over older local context.
8) You should answer any Luzon-related question using available context.
`.trim(); // generated by AI

  const chatHistory = [];
  let brainText = '';
  let brainChunks = [];
  let pageContext = '';
  const derivedFacts = {
    centralLuzonPopulation2020: null,
    centralLuzonShareOfLuzonPct: null,
    luzonPopulation2020Approx: null,
  };
  const parsedProvincePopulation2020 = {};

  const setOpenState = (isOpen) => {
    chatPanel.classList.toggle('open', isOpen);
    chatPanel.setAttribute('aria-hidden', String(!isOpen));
    chatToggle.setAttribute('aria-expanded', String(isOpen));
    if (isOpen && input) input.focus();
  };

  const addMessage = (role, text, options = {}) => {
    if (!messagesEl) return null;
    const messageWrap = document.createElement('div');
    messageWrap.className = `ai-chat-message ${role}${
      options.pending ? ' pending' : ''
    }`;

    const bubble = document.createElement('div');
    bubble.className = 'ai-chat-bubble';
    bubble.textContent = text;

    messageWrap.appendChild(bubble);
    messagesEl.appendChild(messageWrap);
    messagesEl.scrollTop = messagesEl.scrollHeight;
    return bubble;
  };

  const setInputDisabled = (disabled) => {
    if (input) input.disabled = disabled;
    if (sendBtn) sendBtn.disabled = disabled;
  };

  const cleanText = (value) => value.replace(/\s+/g, ' ').trim();
  const parseNumeric = (value) => Number((value || '').replace(/,/g, ''));
  const formatNumeric = (value) =>
    Number.isFinite(value) ? new Intl.NumberFormat('en-US').format(Math.round(value)) : '';
  const hasLatestIntent = (value) =>
    /(latest|current|recent|today|updated|as of|newest)/i.test(value || '');
  const isLuzonRelatedQuery = (value) => {
    const q = (value || '').toLowerCase();
    if (!q) return false;
    return LUZON_TERMS.some((term) => q.includes(term));
  };
  const hasDynamicIntent = (value) =>
    /(latest|current|recent|today|updated|as of|newest|population|governor|vice governor|mayor|representative|official|chairperson|price|inflation|weather|history|tourism|festival|culture|agriculture|economy)/i.test(
      value || '',
    ) || isLuzonRelatedQuery(value);

  const fetchJSONWithTimeout = async (url, options = {}) => {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), LIVE_LOOKUP_TIMEOUT_MS);
    try {
      const response = await fetch(url, {
        ...options,
        signal: controller.signal,
        cache: 'no-store',
      });
      if (!response.ok) return null;
      return await response.json();
    } catch (error) {
      return null;
    } finally {
      clearTimeout(timer);
    }
  };

  const fetchWorldBankPHPopulation = async () => {
    const url =
      'https://api.worldbank.org/v2/country/PHL/indicator/SP.POP.TOTL?format=json&per_page=6';
    const data = await fetchJSONWithTimeout(url);
    if (!Array.isArray(data) || !Array.isArray(data[1])) return null;

    const row = data[1].find((entry) => Number.isFinite(Number(entry && entry.value)));
    if (!row) return null;
    return {
      year: row.date,
      value: Number(row.value),
      source: 'World Bank API',
    };
  };

  const fetchWikipediaSummaries = async (query, limit = 4) => {
    const searchUrl = `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(
      query,
    )}&srlimit=${Math.max(1, Math.min(limit, 6))}&format=json&origin=*`;
    const searchData = await fetchJSONWithTimeout(searchUrl);
    const hits =
      searchData &&
      searchData.query &&
      Array.isArray(searchData.query.search)
        ? searchData.query.search
        : [];
    if (!hits.length) return [];

    const summaries = [];
    for (const hit of hits) {
      const title = hit && hit.title ? hit.title : '';
      if (!title) continue;
      const summaryUrl = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(
        title.replace(/\s+/g, '_'),
      )}`;
      const summary = await fetchJSONWithTimeout(summaryUrl);
      if (!summary || !summary.extract) continue;
      summaries.push({
        title: summary.title || title,
        extract: cleanText(summary.extract).slice(0, 320),
        updated: summary.timestamp || '',
      });
    }
    return summaries;
  };

  const getLiveContextBundle = async (query) => {
    if (!hasDynamicIntent(query)) {
      return { text: '', facts: {} };
    }

    const facts = {};
    const parts = [];
    const lower = (query || '').toLowerCase();

    if (
      lower.includes('population') &&
      (lower.includes('philippines') || lower.includes('pilipinas'))
    ) {
      const wb = await fetchWorldBankPHPopulation();
      if (wb && Number.isFinite(wb.value)) {
        facts.phPopulationLatest = wb;
        parts.push(
          `LIVE Population (${wb.source}): Philippines = ${formatNumeric(
            wb.value,
          )} (${wb.year}).`,
        );
      }
    }

    const wikiQueryVariants = [query];
    if (isLuzonRelatedQuery(query) && !/\bluzon\b/i.test(query || '')) {
      wikiQueryVariants.push(`${query} Luzon Philippines`);
    }

    const matchedTerms = LUZON_TERMS.filter((term) =>
      lower.includes(term),
    ).slice(0, 2);
    matchedTerms.forEach((term) => {
      const variant = `${term} Philippines`;
      if (!wikiQueryVariants.includes(variant)) wikiQueryVariants.push(variant);
    });

    const wikiResults = await Promise.all(
      wikiQueryVariants.slice(0, 3).map((variant) =>
        fetchWikipediaSummaries(variant, 3),
      ),
    );

    const seenTitles = new Set();
    const wikiSummaries = wikiResults
      .flat()
      .filter((item) => {
        const key = (item && item.title ? item.title : '').toLowerCase();
        if (!key || seenTitles.has(key)) return false;
        seenTitles.add(key);
        return true;
      })
      .slice(0, 7);

    if (wikiSummaries.length) {
      const wikiText = wikiSummaries
        .map((item) => {
          const stamp = item.updated ? ` (updated: ${item.updated})` : '';
          return `${item.title}${stamp}: ${item.extract}`;
        })
        .join('\n');
      parts.push(`LIVE Wikipedia summaries:\n${wikiText}`);
    }

    if (isLuzonRelatedQuery(query) && !wikiSummaries.length) {
      const fallbackSummaries = await fetchWikipediaSummaries(
        'Luzon Philippines geography history economy',
        3,
      );
      if (fallbackSummaries.length) {
        const fallbackText = fallbackSummaries
          .map((item) => `${item.title}: ${item.extract}`)
          .join('\n');
        parts.push(`LIVE Luzon fallback summaries:\n${fallbackText}`);
      }
    }

    return {
      text: cleanText(parts.join('\n\n')).slice(0, LIVE_CONTEXT_MAX_CHARS),
      facts,
    };
  };

  const tokenize = (value) =>
    (value.toLowerCase().match(/[a-z0-9]+/g) || []).filter(Boolean);

  const STOP_WORDS = new Set([
    'the',
    'a',
    'an',
    'and',
    'or',
    'is',
    'are',
    'was',
    'were',
    'to',
    'of',
    'in',
    'on',
    'for',
    'with',
    'at',
    'by',
    'from',
    'that',
    'this',
    'it',
    'as',
    'be',
    'about',
    'what',
    'who',
    'when',
    'where',
    'how',
    'which',
    'can',
    'could',
    'should',
    'please',
    'you',
    'your',
    'me',
    'my',
    'i',
    'we',
    'our',
  ]);

  const extractPageContext = () => {
    const selectors = [
      'h1',
      '.s1-desc',
      '.history-intro',
      '.culture-desc',
      '.section-sub',
      '.gov-intro-text',
    ];
    const lines = [];

    selectors.forEach((selector) => {
      const node = document.querySelector(selector);
      if (!node) return;
      const text = cleanText(node.textContent || '');
      if (text) lines.push(text);
    });

    const title = cleanText(document.title || '');
    if (title) lines.unshift(title);

    return cleanText(lines.join(' | ')).slice(0, 1200);
  };

  const buildBrainChunks = (raw) => {
    const normalized = raw.replace(/\r/g, '');
    const paragraphChunks = normalized
      .split(/\n{2,}/)
      .map((chunk) => cleanText(chunk))
      .filter((chunk) => chunk.length >= 35);
    const lineChunks = normalized
      .split('\n')
      .map((line) => cleanText(line))
      .filter((line) => line.length >= 35);

    return Array.from(new Set([...paragraphChunks, ...lineChunks]));
  };

  const deriveFactsFromBrain = (raw) => {
    const compact = cleanText(raw || '');
    if (!compact) return;

    const luzonShareMatch = compact.match(
      /population as determined by the 2020 Census was\s*([\d,]+)\.\s*This represented\s*([\d.]+)% of the overall population of the Luzon island group/i,
    );
    if (luzonShareMatch) {
      const centralPop = parseNumeric(luzonShareMatch[1]);
      const sharePct = Number(luzonShareMatch[2]);
      if (Number.isFinite(centralPop) && Number.isFinite(sharePct) && sharePct > 0) {
        derivedFacts.centralLuzonPopulation2020 = centralPop;
        derivedFacts.centralLuzonShareOfLuzonPct = sharePct;
        derivedFacts.luzonPopulation2020Approx = centralPop / (sharePct / 100);
      }
    }

    if (!derivedFacts.centralLuzonPopulation2020) {
      const centralOnlyMatch = compact.match(
        /Central Luzon[^.]{0,220}population[^.]{0,120}2020 Census[^.]{0,80}\s([\d,]{5,})/i,
      );
      if (centralOnlyMatch) {
        const centralPop = parseNumeric(centralOnlyMatch[1]);
        if (Number.isFinite(centralPop)) {
          derivedFacts.centralLuzonPopulation2020 = centralPop;
        }
      }
    }

    const escapedNames = REGION3_PROVINCES.map((name) =>
      name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'),
    ).join('|');

    const provinceRegex = new RegExp(
      `\\b(${escapedNames})\\b[^.\\n]{0,220}2020 Census was\\s*([\\d,]{4,})`,
      'gi',
    );
    let match = provinceRegex.exec(compact);
    while (match) {
      const province = match[1].toLowerCase();
      const population = parseNumeric(match[2]);
      if (Number.isFinite(population)) {
        parsedProvincePopulation2020[province] = population;
      }
      match = provinceRegex.exec(compact);
    }
  };

  const getDirectFactAnswer = (query, liveFacts = {}) => {
    const q = (query || '').toLowerCase();
    const asksPopulation =
      q.includes('population') ||
      q.includes('populasyon') ||
      q.includes('how many people') ||
      q.includes('ilang tao');

    if (!asksPopulation) return '';

    const asksLuzon = q.includes('luzon');
    if (asksLuzon && Number.isFinite(VERIFIED_FACTS.luzonPopulation2020)) {
      const luzonPop = formatNumeric(VERIFIED_FACTS.luzonPopulation2020);
      if (hasLatestIntent(q)) {
        return `Latest official Luzon island-group count in this dataset is the 2020 Census: ${luzonPop}.`;
      }
      return `As of the 2020 Census, Luzon island group population is ${luzonPop}.`;
    }

    const asksCentral = q.includes('central luzon') || q.includes('region iii') || q.includes('region 3');
    if (asksCentral && Number.isFinite(VERIFIED_FACTS.centralLuzonPopulation2020)) {
      const centralPop = formatNumeric(VERIFIED_FACTS.centralLuzonPopulation2020);
      return `As of the 2020 Census, Central Luzon (Region III) population is ${centralPop}.`;
    }

    if (q.includes('philippines') && Number.isFinite(VERIFIED_FACTS.philippinesPopulation2020)) {
      if (
        liveFacts.phPopulationLatest &&
        Number.isFinite(liveFacts.phPopulationLatest.value)
      ) {
        return `Latest available estimate is Philippines population ${formatNumeric(
          liveFacts.phPopulationLatest.value,
        )} (${liveFacts.phPopulationLatest.year}, World Bank).`;
      }
      const phPop = formatNumeric(VERIFIED_FACTS.philippinesPopulation2020);
      return `As of the 2020 Census, the Philippines population is ${phPop}.`;
    }

    for (const province of REGION3_PROVINCES) {
      if (!q.includes(province)) continue;
      const pop = parsedProvincePopulation2020[province];
      if (Number.isFinite(pop)) {
        return `As of the 2020 Census, ${province.replace(/\b\w/g, (m) => m.toUpperCase())} population is ${formatNumeric(pop)}.`;
      }
    }

    return '';
  };

  const getDateTimeDirectAnswer = (query) => {
    const q = (query || '').toLowerCase();
    const now = new Date();

    const asksYear =
      /\b(what year|current year|year now|year is now|anong taon|taon ngayon)\b/i.test(
        q,
      ) ||
      (q.includes('year') && (q.includes('now') || q.includes('current')));
    if (asksYear) {
      return `The current year is ${now.getFullYear()}.`;
    }

    const asksDate =
      /\b(today'?s date|date today|current date|anong petsa|petsa ngayon)\b/i.test(
        q,
      ) || (q.includes('date') && (q.includes('today') || q.includes('current')));
    if (asksDate) {
      const dateText = new Intl.DateTimeFormat('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }).format(now);
      return `Today's date is ${dateText}.`;
    }

    const asksTime =
      /\b(what time|current time|time now|oras ngayon)\b/i.test(q) ||
      (q.includes('time') && (q.includes('now') || q.includes('current')));
    if (asksTime) {
      const timeText = new Intl.DateTimeFormat('en-US', {
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: true,
      }).format(now);
      return `Current time is ${timeText}.`;
    }

    return '';
  };

  const scoreChunk = (chunk, queryTerms) => {
    if (!queryTerms.length) return 0;
    const chunkTerms = new Set(tokenize(chunk));
    let score = 0;

    queryTerms.forEach((term) => {
      if (chunkTerms.has(term)) {
        score += term.length >= 6 ? 3 : 1;
      }
    });

    return score;
  };

  const getRelevantBrainContext = (query) => {
    if (!brainChunks.length) return '';

    const queryTerms = tokenize(query).filter((term) => !STOP_WORDS.has(term));
    const scored = brainChunks
      .map((chunk) => ({
        chunk,
        score: scoreChunk(chunk, queryTerms),
      }))
      .filter((entry) => entry.score > 0)
      .sort((a, b) => b.score - a.score);

    const selected = [];
    let total = 0;
    const pool = scored.length ? scored : brainChunks.slice(0, 4).map((chunk) => ({ chunk }));

    for (const item of pool) {
      if (total + item.chunk.length > MAX_CONTEXT_CHARS) break;
      selected.push(item.chunk);
      total += item.chunk.length;
      if (selected.length >= 5) break;
    }

    return selected.join('\n');
  };

  const loadBrainContext = async () => {
    for (const path of BRAIN_PATHS) {
      try {
        const response = await fetch(path, { cache: 'no-store' });
        if (!response.ok) continue;
        const text = await response.text();
        if (!text || !text.trim()) continue;
        brainText = text;
        brainChunks = buildBrainChunks(text);
        deriveFactsFromBrain(text);
        return true;
      } catch (error) {
        // Try next candidate path.
      }
    }
    return false;
  };

  const shortenReply = (reply) => {
    const cleaned = cleanText(reply);
    if (cleaned.length <= MAX_REPLY_CHARS) return cleaned;

    const cut = cleaned.slice(0, MAX_REPLY_CHARS);
    const sentenceEnd = Math.max(cut.lastIndexOf('. '), cut.lastIndexOf('? '));
    if (sentenceEnd > 160) return cut.slice(0, sentenceEnd + 1);
    return `${cut}...`;
  };

  const buildRequestMessages = (userText, liveContext = '') => {
    const relevantBrain = getRelevantBrainContext(userText);
    const history = chatHistory.slice(-MAX_HISTORY_ITEMS);
    const verifiedFactsContext = `VERIFIED_FACTS:
- Luzon island group population (2020 Census): ${formatNumeric(VERIFIED_FACTS.luzonPopulation2020)}
- Philippines population (2020 Census): ${formatNumeric(VERIFIED_FACTS.philippinesPopulation2020)}
- Central Luzon / Region III population (2020 Census): ${formatNumeric(VERIFIED_FACTS.centralLuzonPopulation2020)}`;

    const contextMessage = [
      verifiedFactsContext,
      `LIVE_CONTEXT: ${liveContext || 'Not fetched or unavailable.'}`,
      `BRAIN_CONTEXT: ${relevantBrain || 'No local brain context loaded.'}`,
      `CURRENT_PAGE_CONTEXT: ${pageContext || 'No page context extracted.'}`,
    ].join('\n\n');

    return [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'system', content: contextMessage },
      ...history,
      { role: 'user', content: userText },
    ];
  };

  const requestCompletionWithFallback = async (requestMessages) => {
    let lastError = null;

    for (let i = 0; i < modelCandidates.length; i += 1) {
      const model = modelCandidates[i];
      const response = await fetch(
        'https://api.groq.com/openai/v1/chat/completions',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model,
            messages: requestMessages,
            temperature: 0.1,
            max_completion_tokens: 220,
          }),
        },
      );

      const raw = await response.text();
      let data = null;
      try {
        data = raw ? JSON.parse(raw) : null;
      } catch (parseError) {
        data = null;
      }

      if (response.ok) {
        return { data, model };
      }

      const apiMessage =
        data && data.error && data.error.message ? data.error.message : raw;

      lastError = new Error(apiMessage || `Groq API error: ${response.status}`);

      const canTryNextModel =
        i < modelCandidates.length - 1 &&
        /model|unsupported|not found|decommission|invalid/i.test(
          String(apiMessage || ''),
        );

      if (!canTryNextModel) {
        throw lastError;
      }
    }

    throw lastError || new Error('Groq API error');
  };

  chatToggle.addEventListener('click', () => {
    const isOpen = !chatPanel.classList.contains('open');
    setOpenState(isOpen);
  });

  if (closeBtn) {
    closeBtn.addEventListener('click', () => {
      setOpenState(false);
    });
  }

  document.addEventListener('keydown', (event) => {
    if (event.key === 'Escape' && chatPanel.classList.contains('open')) {
      setOpenState(false);
    }
  });

  addMessage(
    'assistant',
    'Hi, I am Luzonix. I will use the local brain file first, then answer briefly and accurately.',
  );

  if (!apiKey) {
    addMessage(
      'assistant',
      'API key missing. Set window.GROQ_API_KEY to enable chat responses.',
    );
    setInputDisabled(true);
  }

  if (!form || !input) return;

  pageContext = extractPageContext();
  const brainReadyPromise = loadBrainContext();

  form.addEventListener('submit', async (event) => {
    event.preventDefault();
    const text = input.value.trim();
    if (!text) return;

    addMessage('user', text);
    input.value = '';

    const pendingBubble = addMessage('assistant', 'Checking local brain context...', {
      pending: true,
    });

    try {
      if (!apiKey) throw new Error('Missing Groq API key.');
      setInputDisabled(true);

      const dateTimeDirect = getDateTimeDirectAnswer(text);
      if (dateTimeDirect) {
        const quickReply = shortenReply(dateTimeDirect);
        if (pendingBubble) pendingBubble.textContent = quickReply;
        chatHistory.push({ role: 'user', content: text });
        chatHistory.push({ role: 'assistant', content: quickReply });
        return;
      }

      await brainReadyPromise;
      const liveBundle = await getLiveContextBundle(text);
      const directAnswer = getDirectFactAnswer(text, liveBundle.facts || {});
      if (directAnswer) {
        const finalDirectReply = shortenReply(directAnswer);
        if (pendingBubble) pendingBubble.textContent = finalDirectReply;
        chatHistory.push({ role: 'user', content: text });
        chatHistory.push({ role: 'assistant', content: finalDirectReply });
        return;
      }

      const requestMessages = buildRequestMessages(text, liveBundle.text || '');
      const { data } = await requestCompletionWithFallback(requestMessages);

      const reply =
        data &&
        data.choices &&
        data.choices[0] &&
        data.choices[0].message &&
        data.choices[0].message.content
          ? data.choices[0].message.content
          : "I'm sorry, I can't answer that right now.";

      const finalReply = shortenReply(reply);
      if (pendingBubble) pendingBubble.textContent = finalReply;

      chatHistory.push({ role: 'user', content: text });
      chatHistory.push({ role: 'assistant', content: finalReply });
    } catch (error) {
      const message =
        error && error.message
          ? error.message
          : 'An unexpected error occurred. Please try again later.';
      if (pendingBubble) pendingBubble.textContent = message;
    } finally {
      setInputDisabled(false);
      if (input) input.focus();
    }
  });
});

//idk 